[Theme]
name = No Port Border
name[fr] = Ports sans bordure

[aliases]
decorations = #d3d3d3
background = #181818
audio = #006da3
midi = #ca6f2d
cv = #7a8ff5
alsa = #4d9c42
video = #8f0038
audiotext = #33bbff
videotext = #ddaab0
porttext = #d2d2d2
box_border = #555555
discret = #333333

[body]
background = background
monitor-color = #be9e00
thumbnail_port_colors = border
port-height = 14

[box_wrapper]
background = transparent
border-color = decorations * 0.8
border-mode = minimal

[rubberband]
border-color = box_border * 1.2
background = background * 1.1
border-style=dashdot

[box]
background = background ** 0.8
border-color = transparent
border-radius = 2
text-color = #e1e1e1
font-name = DejaVu Sans Mono
font-size = 12
font-width = 75
port-in-offset = -1
port-out-offset = -1
port-spacing = 4
port-type-spacing = 4

[box.selected]
border-color = box_border
border-style = dashdot

[box.client]
port-out-offset = 4
port-in-offset = 4

[box.hardware]
port-out-offset = 0
port-in-offset = 0

[box_shadow]
background = #1f1f1f

[port]
border-mode = minimal
text-color = porttext
font-name = DejaVu Sans Mono
font-size = 11
font-width = 50
background = background ** 0.5
output-align = right

[port.audio]
border-color = audio
text-color = audiotext

[port.audio.selected]
background = audio ** 0.25
text-color = porttext

[port.midi]
border-color = midi
text-color = midi * 1.5

[port.midi.selected]
background = midi ** 0.25
text-color = porttext

[port.cv]
border-color = cv
text-color = cv * 1.1

[port.cv.selected]
background = cv ** 0.25
text-color = porttext

[port.alsa]
border-color = alsa
text-color = alsa * 1.2

[port.alsa.selected]
background = alsa ** 0.25
text-color = porttext

[port.video]
border-color = video
text-color = video * 1.5

[port.video.selected]
background = video ** 0.25
text-color = porttext

[portgroup]
inherits = port

[line]
border-width = 1.75

[line.disconnecting]
background = discret
border-width = 1.5

[line.selected]
border-width = 2.25

[line.audio]
background = audio
background2 = audio * 0.9

[line.audio.selected]
background = audio * 1.5

[line.midi]
background = midi

[line.midi.selected]
background = midi * 1.6

[line.alsa]
background = alsa

[line.alsa.selected]
background = alsa * 1.9

[line.video]
background = video

[line.video.selected]
background = video * 1.5

[hardware_rack]
border-mode = minimal
background = transparent
border-color = box_border

[gui_button]
background = transparent
border-radius = 0

[gui_button.gui_visible]
border-color = #aaaaaa
border-width = 1.0
border-mode = minimal

[gui_button.gui_hidden]
border-color = discret
border-mode = sides

[monitor_decoration]
background = transparent
border-color = #887700 ** 0.50
border-width = 1.0
border-mode = minimal

[box_header_line]
border-color = decorations * 0.8
border-width = 1

[grid]
border-color = #202020
border-width = 0.5

[grid.grid]
border-width = 1.0
grid-min-width = 100
grid-min-height = 100

[grid.chessboard]
border-color = #1b1b1b

